* Question 2

* Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.Using these packages [random, strings]

In [58]:
import random
import string
def generate_password(length):
    oneuppercase = random.choices(string.ascii_uppercase, k=1)
    twolowercase= random.choices(string.ascii_lowercase, k=2)
    twodigits=random.choices(string.digits, k=2)
    special=random.choices(string.punctuation, k=1)
    password = "".join(
        random.sample(oneuppercase + twolowercase+twodigits+special, k=length)
    )

    return password


print("Generated Password: " ,generate_password(6))

Generated Password:  5pi=6H


* Question 3
* Create 2D array and update the same 2D array provided that every  prime number position should be replaced by cube of the positioned number

In [5]:
import numpy as np

from primePy import primes

def board():
    list1=[i for i in range(12)]
    for i in list1:
        if primes.check(i)==True and i!=1:
            list1[i]=list1[i]**3
    arr=np.array(list1).reshape(3,4)
    return arr
        
      


* Question 4
* Python program to get the sum of every cubed value and its previous integer.

In [152]:
def check_list(input,rows,columns):
    new_input=[]
    for i,j in enumerate(input):
        if check_cube(j)==True:
            new_input.insert(i,j+input[i-1])
        else:
            new_input.insert(i,input[i])
    return np.array(new_input).reshape(rows,columns)
def check_cube(inp):
    count=0
    for i in range(inp):
        new=i*i*i
        if new==inp:
            return True
            count=1
            break
    if count==0:
        return False
    
            

In [153]:
rows=int(input("Enter the no of rows: "))
columns=int(input("Enter the no of columns"))
elements=rows*columns
list2=[]
for i in range(elements):
    list2.append(int(input("Enter the elements: ")))
check_list(list2,rows,columns)

Enter the no of rows: 2
Enter the no of columns3
Enter the elements: 0
Enter the elements: 1
Enter the elements: 8
Enter the elements: 27
Enter the elements: 4
Enter the elements: 125


array([[  0,   1,   9],
       [ 35,   4, 129]])

###### *Given two arrays, find their intersection. Examples:
Input:  arr1[] = [1, 3, 4, 5, 7] arr2[] = [2, 3, 5, 6]

In [158]:

arr1=np.array([1, 3, 4, 5, 7] )
arr2=np.array([2, 3, 5, 6])
              
print(" Intersected array: ",np.intersect1d(arr1,arr2))


 Intersected array:  [3 5]


*Question
 
* Create a 7 x 7  2D array having only multiples of 7. And return the last  element of the same

In [9]:

sevend=np.array([i for i in range(7,350,7)]).reshape(7,7)
print(sevend)
print("Last element of the array is: ",sevend[-1,-1])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
Last element of the array is:  343


In [20]:
checker=np.zeros(35).reshape(5,7)
checker[::2,::2]=1
checker[1::2,1::2]=1
checker

array([[1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.]])

In [54]:
new_list=['A','B','C','D','E','F','G','H','I','a','K','L','M','N','o','P','Q','R','S','T','U','0','W','O']
for i,j in enumerate(new_list):
    if j.lower() in ['a','e','i','o','u']:
        new_list[i]=np.nan
array_1=np.array(new_list).reshape(6,4)
null_count=0
for i in range(6):
    for j in range(4):
        if array_1[i][j]=='nan':
            null_count+=1
print(array_1)
print("Null values:",null_count)


[['nan' 'B' 'C' 'D']
 ['nan' 'F' 'G' 'H']
 ['nan' 'nan' 'K' 'L']
 ['M' 'N' 'nan' 'P']
 ['Q' 'R' 'S' 'T']
 ['nan' '0' 'W' 'nan']]
Null values: 7


In [55]:
import os
import hashlib
from pathlib import Path
def find_duplicate(path):
    list_of_files = os.walk(path)
    unique_files=dict()
    for root,folder,files in list_of_files:
        for file in files:
            file_path = Path(os.path.join(root, file))
            Hash_file = hashlib.md5(open(file_path, 'rb').read()).hexdigest()
            if Hash_file not in unique_files:
                unique_files[Hash_file] = file_path
            else:
                print("Duplicate file: ",file)
                os.remove(file_path)
                print(f"{file_path} has been deleted")
    

    

In [56]:
find_duplicate('D:/test/')

Duplicate file:  dupfile.txt
D:\test\test1\dupfile.txt has been deleted
